// File generated by Antigravity Agent.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXV2PMoyH-UKLOSj-IxynF1Gftdby1IZc',
    appId: '1:597671358744:web:b654970539d255867e2e6d',
    messagingSenderId: '597671358744',
    projectId: 'galagate-monkey-species',
    authDomain: 'galagate-monkey-species.firebaseapp.com',
    databaseURL: 'https://galagate-monkey-species-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'galagate-monkey-species.firebasestorage.app',
    measurementId: 'G-CM4Q60R8HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiROOw6arBvzcFnHtKw87d2Y2FJoELD0c',
    appId: '1:597671358744:android:4d31c435b13973b57e2e6d',
    messagingSenderId: '597671358744',
    projectId: 'galagate-monkey-species',
    databaseURL: 'https://galagate-monkey-species-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'galagate-monkey-species.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB8-hb44zNm5YL3DbALtKP2yd7KLUFT1U',
    appId: '1:597671358744:ios:10104cb42b0ece017e2e6d',
    messagingSenderId: '597671358744',
    projectId: 'galagate-monkey-species',
    databaseURL: 'https://galagate-monkey-species-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'galagate-monkey-species.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB8-hb44zNm5YL3DbALtKP2yd7KLUFT1U',
    appId: '1:597671358744:ios:10104cb42b0ece017e2e6d',
    messagingSenderId: '597671358744',
    projectId: 'galagate-monkey-species',
    databaseURL: 'https://galagate-monkey-species-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'galagate-monkey-species.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXV2PMoyH-UKLOSj-IxynF1Gftdby1IZc',
    appId: '1:597671358744:web:b654970539d255867e2e6d',
    messagingSenderId: '597671358744',
    projectId: 'galagate-monkey-species',
    authDomain: 'galagate-monkey-species.firebaseapp.com',
    databaseURL: 'https://galagate-monkey-species-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'galagate-monkey-species.firebasestorage.app',
    measurementId: 'G-CM4Q60R8HT',
  );
}
