import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'landingpage.dart'; // Import Landing Page (needed for routes if any)
import 'screens/splash_screen.dart'; // Import Splash Screen
import 'firebase_options.dart'; // <- generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MonkeyIdApp());
}

class MonkeyIdApp extends StatelessWidget {
  const MonkeyIdApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Monkey Species',
      theme: ThemeData(
        brightness: Brightness.dark,
        primarySwatch: Colors.green,
      ),
      home: const SplashScreen(), // Set Splash Screen as the entry point
    );
  }
}
